version: "3"

services:
    nest-api:
        build: ./nest-api
        entrypoint: ./.docker/entrypoint.sh
        ports:
            - 3000:3000
        volumes:
            - ./nest-api:/home/node/nest_api

    front:
        build: ./front
        entrypoint: ./.docker/entrypoint.sh
        ports:
            - 3001:3000
        volumes:
            - ./front:/home/node/front
        depends_on:
            - nest-api